---
- name: Create directory
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ haproxy_global_user }}"
    group: "{{ haproxy_global_group }}"
  when:
    - haproxy_copy_files | length > 0
  with_items: "{{ haproxy_copy_files }}"

- name: Copy Content from Controller to HaProxy
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.path }}/{{ item.dest | default('file.html') }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  when:
    - haproxy_copy_files | length > 0
    - item.content is defined
  notify: reload haproxy
  with_items: "{{ haproxy_copy_files }}"
